basePath: /api
definitions:
  request.Project:
    properties:
      alias:
        example: PA
        type: string
      description:
        example: Description of the Project A.
        type: string
      is_active:
        example: true
        type: boolean
      name:
        example: Project A
        type: string
    type: object
  response.ErrorMessage:
    properties:
      invalid_fields:
        items:
          $ref: '#/definitions/response.InvalidField'
        type: array
      message:
        type: string
      status_code:
        type: integer
    type: object
  response.ID:
    properties:
      id:
        type: string
    type: object
  response.InvalidField:
    properties:
      description:
        type: string
      field_name:
        type: string
    type: object
  response.Project:
    properties:
      alias:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      description:
        type: string
      id:
        type: string
      is_active:
        type: boolean
      name:
        type: string
      updated_at:
        type: string
    type: object
info:
  contact:
    email: fss30@aluno.ifal.edu.br
    name: Felipe da Silva Santos
  description: RMS backend API
  title: RMS API
  version: "1.0"
paths:
  /projects:
    get:
      description: Rota que permite a listagem dos projetos.
      operationId: Project.List
      produces:
      - application/json
      responses:
        "201":
          description: Requisição realizada com sucesso.
          schema:
            items:
              $ref: '#/definitions/response.Project'
            type: array
        "400":
          description: Requisição mal formulada.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "401":
          description: Usuário não autorizado.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "403":
          description: Acesso negado.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "404":
          description: Recurso não encontrado.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "422":
          description: Ocorreu um erro de validação de dados. Vefique os valores,
            tipos e formatos de dados enviados.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "500":
          description: Ocorreu um erro inesperado. Por favor, contate o suporte.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "503":
          description: A base de dados está temporariamente indisponível.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
      summary: Listar projetos
      tags:
      - Projetos
    post:
      consumes:
      - application/json
      description: Rota que permite o cadastro de um projeto.
      operationId: Project.Create
      parameters:
      - description: JSON com todos os dados necessários para se cadastrar um projeto.
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.Project'
      produces:
      - application/json
      responses:
        "201":
          description: Requisição realizada com sucesso.
          schema:
            $ref: '#/definitions/response.ID'
        "400":
          description: Requisição mal formulada.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "401":
          description: Usuário não autorizado.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "403":
          description: Acesso negado.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "404":
          description: Recurso não encontrado.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "422":
          description: Ocorreu um erro de validação de dados. Vefique os valores,
            tipos e formatos de dados enviados.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "500":
          description: Ocorreu um erro inesperado. Por favor, contate o suporte.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "503":
          description: A base de dados está temporariamente indisponível.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
      summary: Cadastrar projeto
      tags:
      - Projetos
swagger: "2.0"
