// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package connector

import (
	"database/sql"
	"time"
)

type AcceptanceCriterium struct {
	ID            int32
	RequirementID int32
	CreatedAt     time.Time
	UpdatedAt     sql.NullTime
	DeletedAt     sql.NullTime
}

type Actor struct {
	ID          int32
	Name        string
	Description sql.NullString
}

type ActorIsAssociatedWithRequirement struct {
	ActorID       int32
	RequirementID int32
}

type CustomField struct {
	ID          int32
	Name        string
	Description sql.NullString
	TypeID      int32
}

type CustomFieldType struct {
	ID   int32
	Name string
}

type Label struct {
	ID   int32
	Name string
}

type Priority struct {
	ID    int32
	Level string
}

type Project struct {
	ID          int32
	Name        string
	Alias       sql.NullString
	Description sql.NullString
	IsActive    sql.NullBool
	CreatedAt   time.Time
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type Requirement struct {
	ID          int32
	Code        string
	Title       string
	Description sql.NullString
	UserStory   sql.NullString
	TypeID      int32
	OriginID    int32
	PriorityID  int32
	ProjectID   int32
	CreatedAt   time.Time
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type RequirementDependsOnRequirement struct {
	DependentID    int32
	PrerequisiteID int32
}

type RequirementHasCustomField struct {
	RequirementID int32
	CustomFieldID int32
	Value         sql.NullString
}

type RequirementHasLabel struct {
	RequirementID int32
	LabelID       int32
}

type RequirementOrigin struct {
	ID   int32
	Name string
}

type RequirementType struct {
	ID   int32
	Name string
}
