TRUNCATE requirement RESTART IDENTITY CASCADE;
TRUNCATE priority RESTART IDENTITY CASCADE;
TRUNCATE requirement_origin RESTART IDENTITY CASCADE;
TRUNCATE requirement_type RESTART IDENTITY CASCADE;

DROP TABLE IF EXISTS requirement;
DROP TABLE IF EXISTS priority;
DROP TABLE IF EXISTS requirement_origin;
DROP TABLE IF EXISTS requirement_type;
